### ISSUE TITLE
New versions of Forge for MC 1.12 are breaking mods, including Fun Ores.

### ISSUE THREAD

**Issue by Zarepheth** [SilentChaos512/FunOres#32]
The newest versions of Forge (14.21.0.2348+) are breaking many mods, Fun Ores amongst them.

Minecraft 1.12
Forge 14.21.0.2359
Fun Ores 1.5.3-109

```
[17:02:15] [main/FATAL] [FML]: The following problems were captured during this phase
[17:02:15] [main/ERROR] [FML]: Caught exception from funores (java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/registry/IForgeRegistryEntry)
```

```
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Fun Ores (funores)
Caused by: java.lang.NoClassDefFoundError: net/minecraftforge/fml/common/registry/IForgeRegistryEntry
	at net.silentchaos512.funores.FunOres.<clinit>(FunOres.java:74)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:552)
	...
```

[Log File on paste.ee](https://paste.ee/p/Ds6Oz)

**Comment by SilentChaos512** [comment]
Thanks for reporting. I was already aware of the issue, just putting the finishing touches on the update.
